const data = {
  products: [
    {
      name: "Free Shirt",
      slug: "free-shirt",
      category: "Shirts",
      image: "./images/shirt1.jpg",
      price: 70,
      brand: "Nike",
      reting: 4.5,
      numReviews: 8,
      countInStock: 20,
      description: "A popular shirt",
    },
    {
      name: "Fit Shirt",
      slug: "fit-shirt",
      category: "Shirts",
      image: "./images/shirt2.jpg",
      price: 80,
      brand: "Adidas",
      reting: 3.2,
      numReviews: 10,
      countInStock: 50,
      description: "A popular shirt",
    },
    {
      name: "Slim  Shirt",
      slug: "slim-shirt",
      category: "Shirts",
      image: "./images/shirt3.jpg",
      price: 100,
      brand: "Raymond",
      reting: 4.5,
      numReviews: 3,
      countInStock: 10,
      description: "A popular shirt",
    },
    {
      name: "Golf Pants",
      slug: "golf-pants",
      category: "Pants",
      image: "./images/pants1.jpg",
      price: 90,
      brand: "Oliver",
      reting: 2.9,
      numReviews: 3,
      countInStock: 10,
      description: "A popular pants",
    },
    {
      name: "Fit Pants",
      slug: "fit-pants",
      category: "Pants",
      image: "./images/pants2.jpg",
      price: 90,
      brand: "Zara",
      reting: 2.9,
      numReviews: 3,
      countInStock: 10,
      description: "A popular pants",
    },
  ],
};

export default data;
